version: "3"

services:
  jammer:
    build:
      context: .
    image: masonkatz/jammer
    hostname: jammer
    environment:
      - JAMBOX_HOST=${JAMBOX_HOST}
      - JAMBOX_USER=${JAMBOX_USER:-jb}
      - JAMBOX_IN1=${JAMBOX_IN1:-22}
    volumes:
      - ${HOME}/.ssh/jammer_rsa:/home/user/.ssh/id_rsa:ro
      - ${HOME}/.ssh/jammer_rsa.pub:/home/user/.ssh/id_rsa.pub:ro
    restart: always
