version: "3"

services:
  jambox:
    build:
      context: .
    image: masonkatz/jambox
    hostname: jambox
    environment:
      - JAMBOX_PASSWORD=${JAMBOX_PASSWORD}
    ports:
      - "${JAMBOX_OUT:-2222}:22"
      - "3128:3128"
